from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "outputs" / "tables"
LOGS = ROOT / "outputs" / "logs"
DESTINATION = ROOT / "public" / "modules" / "flood-cause-evolution" / "data" / "flood-cause-explorer.json"

MECHANISMS = [
    "Dry-Intensity", "Dry-Volume", "Moderate-Intensity",
    "Moderate-Volume", "Wet-Intensity", "Wet-Volume",
]
OUTCOMES = {
    "direct_runoff_volume": {
        "short": "Flood volume",
        "label": "Direct stormflow volume of the selected events",
        "unit": "mm per 10 years",
        "meaning": "The event-scale direct runoff volume associated with the selected large floods.",
        "digits": 2,
    },
    "flood_peak": {
        "short": "Flood peak",
        "label": "Maximum daily streamflow during the selected events",
        "unit": "mm/day per 10 years",
        "meaning": "The largest daily streamflow observed inside each reconstructed event-response window.",
        "digits": 2,
    },
    "exceedance_frequency": {
        "short": "Q95 frequency",
        "label": "Annual frequency of events above the fixed Q95 volume threshold",
        "unit": "events/year per 10 years",
        "meaning": "How many selected large floods occurred per observed year.",
        "digits": 2,
    },
    "mechanism_frequency": {
        "short": "Process frequency",
        "label": "Annual frequency of the selected flood-generating process",
        "unit": "events/year per 10 years",
        "meaning": "How often this process produced a Q95 large flood in the catchment.",
        "digits": 2,
    },
    "mechanism_share": {
        "short": "Process share",
        "label": "Share of selected floods generated by this process",
        "unit": "percentage points per 10 years",
        "meaning": "How this process's percentage of the catchment's selected large floods changed.",
        "digits": 2,
    },
    "rainfall_concentration": {
        "short": "Rainfall concentration",
        "label": "Rainfall concentration within this flood-generating process",
        "unit": "percentage points per 10 years",
        "meaning": "Rainfall concentration is the percentage of total event rainfall falling on the single rainiest day.",
        "digits": 2,
    },
    "antecedent_wetness": {
        "short": "Antecedent wetness",
        "label": "Soil saturation index before events of this process",
        "unit": "SSI units per 10 years",
        "meaning": "The normalized 0–1 soil saturation state preceding the selected events.",
        "digits": 3,
    },
}
MECHANISM_TEXT = {
    "Dry-Intensity": "Peaked rainfall over initially dry soil",
    "Dry-Volume": "Prolonged or distributed rainfall over initially dry soil",
    "Moderate-Intensity": "Peaked rainfall over moderately wet soil",
    "Moderate-Volume": "Prolonged or distributed rainfall over moderately wet soil",
    "Wet-Intensity": "Peaked rainfall over wet soil",
    "Wet-Volume": "Prolonged or distributed rainfall over wet soil",
}


def _native(value: Any, digits: int | None = None) -> Any:
    if value is None or pd.isna(value):
        return None
    if isinstance(value, (bool, np.bool_)):
        return bool(value)
    if isinstance(value, (int, np.integer)):
        return int(value)
    if isinstance(value, (float, np.floating)):
        return round(float(value), digits) if digits is not None else float(value)
    return value


def _metric(row: pd.Series) -> dict[str, Any]:
    return {
        "slope": _native(row.display_slope_per_decade, 6),
        "ci": [_native(row.display_ci_low_per_decade, 6), _native(row.display_ci_high_per_decade, 6)],
        "p": _native(row.p_value, 7),
        "mean": _native(row.mean_level, 6),
        "from": _native(row.fitted_first, 6),
        "to": _native(row.fitted_last, 6),
        "relative": _native(row.get("relative_slope_percent_per_decade"), 5),
        "events": _native(row.n_observations),
        "mechanismEvents": _native(row.get("n_mechanism_events")),
        "years": _native(row.n_years),
        "firstYear": _native(row.first_year),
        "lastYear": _native(row.last_year),
        "span": _native(row.year_span),
        "tau": _native(row.get("mk_tau"), 5),
        "supported": bool(row.supported_shift),
        "pPass": bool(row.p_pass),
        "sampleStable": bool(row.sample_direction_stable),
        "classificationStable": bool(row.classification_direction_stable),
        "leaveOneYearStable": bool(row.leave_one_year_stable),
        "alternatives": {
            "Q90": _native(row.get("pot_q90_slope"), 6),
            "Q97.5": _native(row.get("pot_q975_slope"), 6),
            "Annual maximum": _native(row.get("annual_maximum_slope"), 6),
        },
    }


def _limit(table: pd.DataFrame, outcome: str) -> float:
    values = pd.to_numeric(table.loc[table.outcome.eq(outcome), "display_slope_per_decade"], errors="coerce").dropna().abs()
    if values.empty:
        return 1.0
    value = float(values.quantile(0.95))
    return value if value > 0 else 1.0


def build_web_data() -> dict[str, Any]:
    summary = json.loads((LOGS / "analysis_summary.json").read_text(encoding="utf-8"))
    overall = pd.read_csv(TABLES / "catchment_overall_trends.csv")
    process = pd.read_csv(TABLES / "catchment_mechanism_trends.csv", low_memory=False)
    sample = pd.read_parquet(ROOT / "data" / "derived" / "primary_extreme_events.parquet")
    metadata = sample[["GCIN", "country", "continent", "longitude", "latitude"]].drop_duplicates("GCIN")
    composition = pd.read_csv(TABLES / "mechanism_composition.csv")

    overall_groups = {int(key): frame for key, frame in overall.groupby("GCIN", sort=False)}
    process_groups = {int(key): frame for key, frame in process.groupby("GCIN", sort=False)}
    catchments = []
    for item in metadata.itertuples(index=False):
        gcin = int(item.GCIN)
        overall_metrics = {
            row.outcome: _metric(row)
            for _, row in overall_groups.get(gcin, pd.DataFrame()).iterrows()
        }
        process_metrics: dict[str, dict[str, Any]] = {}
        for _, row in process_groups.get(gcin, pd.DataFrame()).iterrows():
            process_metrics.setdefault(row.mechanism, {})[row.outcome] = _metric(row)
        if not overall_metrics and not process_metrics:
            continue
        catchments.append({
            "id": gcin,
            "country": item.country,
            "continent": item.continent,
            "lon": round(float(item.longitude), 5),
            "lat": round(float(item.latitude), 5),
            "overall": overall_metrics,
            "processes": process_metrics,
        })

    limits = {}
    for outcome in OUTCOMES:
        source = overall if outcome in {"direct_runoff_volume", "flood_peak", "exceedance_frequency"} else process
        limits[outcome] = _limit(source, outcome)
    outcome_meta = {key: {**value, "limit": limits[key]} for key, value in OUTCOMES.items()}

    top = process[process["supported_shift"].fillna(False)].copy()
    top["scaled"] = top["display_slope_per_decade"].abs() / top.groupby("outcome")["display_slope_per_decade"].transform(lambda x: x.abs().median()).replace(0, 1)
    findings = []
    for row in top.nlargest(24, "scaled").itertuples(index=False):
        findings.append({
            "id": int(row.GCIN), "country": row.country, "mechanism": row.mechanism,
            "outcome": row.outcome, "slope": _native(row.display_slope_per_decade, 5),
            "unit": row.display_unit,
        })

    payload = {
        "meta": {
            "title": "Global Flood Cause Evolution",
            "period": "1982–2019",
            "primaryEvents": summary["sample_counts"]["pot_q95"]["events"],
            "primaryCatchments": summary["sample_counts"]["pot_q95"]["catchments"],
            "rankingVariable": "Event direct stormflow volume",
            "outcomes": outcome_meta,
            "mechanisms": [{"id": key, "label": key.replace("-", " + "), "meaning": MECHANISM_TEXT[key]} for key in MECHANISMS],
            "composition": composition.to_dict(orient="records"),
            "supportedOverall": summary["supported_overall_trends"],
            "supportedProcess": summary["supported_mechanism_trends"],
            "figures": [
                {"src": f"reports/assets/figure_0{i}_{name}.png", "alt": alt}
                for i, name, alt in [
                    (1, "sample_and_process_coverage", "Primary sample and six-process composition"),
                    (2, "overall_flood_changes", "Changes in the selected large floods"),
                    (3, "process_frequency_changes", "Process-frequency changes"),
                    (4, "process_share_changes", "Process-share changes"),
                    (5, "process_response_rankings", "Process-specific flood-response rankings"),
                    (6, "example_process_trajectories", "Example process-share trajectories"),
                ]
            ],
            "findings": findings,
            "report": "reports/global_flood_cause_evolution.html",
        },
        "catchments": catchments,
    }
    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    return {"status": "complete", "destination": str(DESTINATION), "catchments": len(catchments), "bytes": DESTINATION.stat().st_size}


if __name__ == "__main__":
    print(json.dumps(build_web_data(), indent=2, ensure_ascii=False))
